workspace:
  path: src

pipeline:
  test-formula:
    image: webhippie/ruby:latest
    pull: true
    commands:
      - rake test

  notify-gitter:
    image: plugins/gitter:1
    pull: true
    secrets: [ gitter_webhook ]
    when:
      local: false
      status: [ success, failure ]
