---
name: general

"on":
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  testing:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        id: source
        uses: actions/checkout@44c2b7a8a4ea60a981eaca3cf939b5f4305c123b # v4

      - name: Setup ruby
        id: ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Run lint
        id: lint
        run: bundle exec rake rubocop

      - name: Run test
        id: test
        run: bundle exec rake spec

...
