---
name: general

"on":
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  testing:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        id: source
        uses: actions/checkout@v3

      - name: Setup ruby
        id: ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1
          bundler-cache: true

      - name: Run rubocop
        id: rubocop
        run: bundle exec rake rubocop

      - name: Run rspec
        id: rspec
        run: bundle exec rake spec

...
